name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    name: macOS
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2
    - name: LFS pull
      run: git lfs pull
    - name: Install Postgres
      run: brew install postgresql@15
    - name: Link Postgres
      run: brew link postgresql@15
    - name: Start Postgres
      run: brew services start postgresql@15
    - name: Select Xcode 14.3
      run: sudo xcode-select -s /Applications/Xcode_14.3.app
    - name: Bootstrap
      run: make bootstrap
    - name: Run tests
      run: make test

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.8
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: 'sudo apt-get --fix-missing update && sudo apt-get install -y wamerican'
    - name: Bootstrap
      run: make bootstrap-client
    - name: Run tests
      run: make test-server-linux
