name: CI

on: [push, pull_request]

jobs:
  mac:
    name: macOS
    runs-on: macOS-11.0
    steps:
    - uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2
    - name: LFS pull
      run: git lfs pull
    - name: Start Postgres
      run: brew services start postgresql
    - name: Select Xcode 13.2.1
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Bootstrap
      run: make bootstrap
    - name: Run tests
      run: make test

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: 'sudo apt-get --fix-missing update && sudo apt-get install -y wamerican'
    - name: Bootstrap
      run: make bootstrap-client
    - name: Run tests
      run: make test-server-linux
